export const EXTENDED_MOCK_PETS = [
    {
        id: 1,
        name: 'Bidu',
        breed: 'Golden Retriever',
        species: 'Cachorro',
        age: 'Adulto',
        size: 'Grande',
        gender: 'Macho',
        weight: '32kg',
        description: 'Bidu é um cachorro extremamente dócil e companheiro. Adora brincar de buscar a bolinha e se dá muito bem com crianças e outros animais. Ele foi resgatado de uma situação de abandono mas hoje está saudável e ansioso para encontrar uma família permanente.',
        location: 'São Paulo, SP',
        image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=612'
    },
    {
        id: 2,
        name: 'Luna',
        breed: 'SRD (Vira-lata)',
        species: 'Cachorro',
        age: 'Filhote',
        size: 'Médio',
        gender: 'Fêmea',
        weight: '8kg',
        description: 'Luna é pura energia! Como todo filhote, adora explorar e morder brinquedos. Ela já tomou as primeiras vacinas e precisa de uma família que tenha tempo para educá-la com muito amor.',
        location: 'Rio de Janeiro, RJ',
        image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=1169'
    },
    {
        id: 3,
        name: 'Thor',
        breed: 'Pastor Alemão',
        species: 'Cachorro',
        age: 'Jovem',
        size: 'Grande',
        gender: 'Macho',
        weight: '28kg',
        description: 'Thor é um jovem Pastor Alemão muito inteligente e protetor. Ele precisa de espaço para correr e de alguém que possa investir tempo em seu treinamento.',
        location: 'Curitiba, PR',
        image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&q=80&w=1074'
    },
    {
        id: 4,
        name: 'Mel',
        breed: 'Beagle',
        species: 'Cachorro',
        age: 'Adulto',
        size: 'Pequeno',
        gender: 'Fêmea',
        weight: '12kg',
        description: 'Mel é uma Beagle dócil e muito farejadora. Adora passeios e é a companhia perfeita para quem gosta de caminhar ao ar livre.',
        location: 'Belo Horizonte, MG',
        image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=694'
    },
    {
        id: 5,
        name: 'Max',
        breed: 'Labrador',
        species: 'Cachorro',
        age: 'Sênior',
        size: 'Grande',
        gender: 'Macho',
        weight: '35kg',
        description: 'Max é um senhor Labrador muito tranquilo. Ele só quer um cantinho confortável para tirar suas sonecas e receber carinho.',
        location: 'Porto Alegre, RS',
        image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=687'
    },
    {
        id: 6,
        name: 'Amora',
        breed: 'Gato Siamês',
        species: 'Gato',
        age: 'Filhote',
        size: 'Pequeno',
        gender: 'Fêmea',
        weight: '1.5kg',
        description: 'Amora é uma gatinha carente e muito brincalhona. Ela adora dormir no colo e ronronar.',
        location: 'Salvador, BA',
        image: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=735'
    },
    {
        id: 7,
        name: 'Simba',
        breed: 'Maine Coon',
        species: 'Gato',
        age: 'Jovem',
        size: 'Grande',
        gender: 'Macho',
        weight: '7kg',
        description: 'Simba é um gato majestoso e independente. Ele gosta de ter seu próprio espaço mas é muito carinhoso quando quer.',
        location: 'São Paulo, SP',
        image: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&q=80&w=735'
    },
    {
        id: 8,
        name: 'Pipoca',
        breed: 'SRD',
        species: 'Gato',
        age: 'Adulto',
        size: 'Médio',
        gender: 'Macho',
        weight: '4kg',
        description: 'Pipoca é um gato muito curioso e ativo. Adora caçar brinquedos de pena e explorar prateleiras altas.',
        location: 'Fortaleza, CE',
        image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&q=80&w=715'
    }
];
